.github/workflows/ci.yaml

add GITHUB_TOKEN

---

.goreleaser.yml

fix archive name

---

.gitignore
.goreleaser.yml
cmd/minecraft-exporter/main.go
go.mod
main.go

rename minecraft-prometheus-exporter to minecraft-exporter #9

---

.gitignore
README.md
pkg/exporter/exporter.go

Rename metrics names from minecraft-prometheus-exporter to minecraft #9

---

README.md
pkg/exporter/exporter.go

Switch API from mojang to https://github.com/Electroid/mojang-api #13

---

README.md
pkg/exporter/exporter.go

Reorganise metric names and add labels

---

pkg/exporter/exporter.go

fix error message for player lookup

---

.goreleaser.yml
renovate.json

Create ARM64 binary

---

.goreleaser.yml

Create Windows and Mac Binaries

---

.github/workflows/ci.yaml
.goreleaser.yml

Add Docker Support

---

.github/workflows/ci.yaml
.goreleaser.yml

Switch to goreleaser v0.176.0 container signing

---

renovate.json

Disable Renovate dependency dashboard

---

.github/workflows/ci.yaml

Update cosign to v1.1.0

---

.github/workflows/ci.yaml
go.mod

Update go to 1.17

---

.gitignore

fix release with ignoring the cosign.pub

---

.github/workflows/ci.yaml

downgrade sigstore/cosign-installer@main

---

.github/workflows/ci.yaml

Update cosign to 1.2.0

---

renovate.json

feat: add "commitBody"

---

README.md

docs: Write a little how to using the minecraft prometheus exporter

---

.golangci.yaml
cmd/minecraftExporter/main.go
main.go
pkg/config/config.go
pkg/exporter/exporter.go

feat: add .golangci.yaml and fix issues

---

cmd/minecraftExporter/main.go
pkg/exporter/exporter.go

fix: linting error

---

.goreleaser.yml

fix: change sign artifacts to archive

---

README.md
pkg/config/config.go

feat: add environment variable support for flags

---

README.md
pkg/exporter/exporter.go

feat: add namespace label to certain metrics.

---

.goreleaser.yaml

feat: add docker manifest support

---

.gitignore
README.md
cmd/minecraftExporter/main.go
pkg/config/config.go

feat: Disabling collection of exporter metrics (like go_*)

feat: Disabling collection of exporter metrics (like go_*)

---

.goreleaser.yaml

fix: error in goreleaser docker_manifests tag

---

.github/workflows/helm-publish.yaml
.pre-commit-config.yaml
.pre-commit-hooks.yaml
README.md
chart/.helmignore
chart/Chart.yaml
chart/README.md
chart/README.md.gotmpl
chart/templates/NOTES.txt
chart/templates/_helpers.tpl
chart/templates/deployment.yaml
chart/templates/podsecuritypolicy.yaml
chart/templates/role.yaml
chart/templates/rolebinding.yaml
chart/templates/service.yaml
chart/templates/serviceaccount.yaml
chart/templates/servicemonitor.yaml
chart/values.yaml
git-hook/helm-docs.sh

feat: add Helm chart

---

.github/workflows/helm-publish.yaml

fix: fix pipeline

---

.github/workflows/helm-publish.yaml

fix: rewrite env variable access

---

.github/workflows/helm-publish.yaml

fix: separate install from run helm-docs

---

.github/configs/cr.yaml
.github/workflows/helm-publish.yaml
charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

feat: add chart release

---

charts/minecraft-exporter/Chart.yaml

feat: add chart logo

---

README.md
charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md
charts/minecraft-exporter/README.md.gotmpl

feat: add ArtifactHub badge

---

CONTRIBUTING.md
DCO
SECURITY.md

docs: add CONTRIBUTING.md, DCO and SECURITY.md

docs: add CONTRIBUTING.md, DCO and SECURITY.md

---

charts/minecraft-exporter/Chart.yaml

chore: update appversion to v0.10.0

---

README.md
cmd/minecraftExporter/main.go
pkg/config/config.go
pkg/exporter/exporter.go

feat: add overall TPS, Ticktime and entity stats for Forge servers

---

charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

chore: update version of container to 0.11.0

---

.github/configs/cr.yaml
charts/minecraft-exporter/Chart.yaml

chore: fix release tag name

---

.github/configs/cr.yaml
.goreleaser.yaml

feat: prepare minecraft-exporter image to upload into ArtifactHub

---

.goreleaser.yaml
CONTAINER.md
README.md
charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md.gotmpl

feat: refine minecraft-exporter image in ArtifactHub

---

.github/configs/cr.yaml
.github/workflows/helm-publish.yaml
charts/minecraft-exporter/Chart.yaml

chore: update helm chart to AppVersion 0.11.2

---

.github/workflows/ci.yaml
.github/workflows/helm-publish.yaml
.github/workflows/lint-and-test.yml
.github/workflows/lint.yaml
.github/workflows/ossf-scorecard-action.yaml
Dockerfile
artifacthub-repo.yml

chore: pin chart actions sha256 and dockerfile FROM

---

.github/workflows/ci.yaml
.github/workflows/helm-publish.yaml

fix: fix the permissions of the pipelines

---

.github/workflows/ci.yaml
.github/workflows/helm-publish.yaml
.github/workflows/lint-and-test.yml
.github/workflows/lint.yaml
.github/workflows/ossf-scorecard-action.yaml

feat: fix actions with renovate annotation

feat: fix actions with renovate annotation

---

pkg/exporter/exporter.go

fix: Failed to connect to api.ashcon.app

---

cmd/minecraftExporter/main.go
pkg/exporter/exporter.go

feat: Reuse RCON connection and reconnect on connection drop

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yaml

feat: add GitHub bug and feature templates

---

.github/workflows/helm-publish.yaml

feat: add Artifact Hub linting for Helm Chart

---

.github/workflows/lint-and-test.yml
charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

feat: Update AppVersion in Helm Chart

feat: Update AppVersion in Helm Chart

---

.github/ISSUE_TEMPLATE/feature.yaml

chore: Add default assignee on feature template

---

.github/PULL_REQUEST_TEMPLATE.md

feat: pull request template

---

go.mod

feat: update to golang 1.18

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml

feat: update to build and release job to golang 1.18

---

README.md
pkg/exporter/exporter.go

feat: handle non-english list message to extract online player

---

charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

feat: update helm chart to use latest release version

---

charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

chore: update appversion to 0.14.1

---

pkg/exporter/exporter.go

feat: handle rename from play_one_minute to play_time in > 1.17

---

charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

feat: update app version in helm chart

---

.github/ISSUE_TEMPLATE/bug.yaml
README.md
charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md
charts/minecraft-exporter/README.md.gotmpl

feat: remove documentation inconsistency

---

cmd/minecraftExporter/main.go

feat: mitigate potential slowloris attack

---

README.md
pkg/config/config.go
pkg/exporter/exporter.go

feat: add PurpurMC TPS support

---

.github/workflows/ci.yaml

chore: update pipeline to golang 1.19

---

.github/workflows/lint-and-test.yml
charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

feat: add trivy support and update appVersion to 0.16.0

---

.github/workflows/lint-and-test.yml

chore: pin version of codeql-action/upload-sarif

---

pkg/exporter/exporter.go

Please reference the issue this PR is fixing. #273 

feat: add whitespace to regex on forge overall tps

---

charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

chore: update helm chart for bugfix in the exporter

---

Dockerfile

feat: switch to distroless base image

---

Dockerfile

feat: move to distroless:static image

---

pkg/exporter/exporter.go

Please reference the issue this PR is fixing. closes #260 

feat: support ShortTag and FloatTag for player health

---

pkg/exporter/exporter.go

Please reference the issue this PR is fixing. Fixes #294 

feat: rework logic to get playerstats

---

charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

feat: update appVersion to 0.16.3 in helm chart

---

Dockerfile

feat: change base image to cgr.dev/chainguard/static

---

.github/workflows/ossf-scorecard-action.yaml

feat: add id-token: write permission

---

.github/workflows/lint-and-test.yml
charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

chore: update appversion

---

.github/workflows/helm-publish.yaml

feat: add publish as OCI registry

---

.github/workflows/helm-publish.yaml

chore: update helm-doc version to 1.11.0

---

.github/workflows/helm-publish.yaml
.pre-commit-config.yaml
README.md
charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md
charts/minecraft-exporter/README.md.gotmpl

feat: remove custom badge code

---

.github/workflows/helm-publish.yaml
charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

feat: add docker login

---

charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md
charts/minecraft-exporter/README.md.gotmpl

feat: update README for OCI instructions

---

README.md

docs: add stargazer chart to README.md

---

.github/workflows/helm-publish.yaml

fix: change way to capture digest from helm push

---

.github/workflows/ci.yaml
go.mod

feat: update to golang 1.20

---

charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

feat: update minecraft-exporter chart

---

charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

chore: update helm chart version

---

pkg/exporter/exporter.go

feat: rewrite if-else to switch statement

---

charts/minecraft-exporter/Chart.yaml
charts/minecraft-exporter/README.md

chore: update helm chart for latest release

---

.gitignore
.golangci.yaml
pkg/exporter/exporter.go

Please reference the issue this PR is fixing. closes #1155

feat: change Electroid's Mojang-API
